version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app.js:/app/app.js
  test:
    build:
      context: .
      dockerfile: Dockerfile.test